version: '3.9'

services:
  django-prd:
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres