version: '3.9'

services:
  django-prd:
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - postgres-prd
  
  postgres-prd:
    image: postgres:15.1-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=passwordgenerator-prd
    volumes:
      - postgres-data-prd:/database:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=sac.94@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

volumes:
  postgres-data-prd: